### ISSUE TITLE
Rel-16 CAS support on rt-mbms-modem (1.2.0) ?

### ISSUE THREAD

**Issue by m-bures** [5G-MAG/rt-mbms-modem#31] opened 2022-03-16 14:10 UTC
We tried to demodulate signal from R&S transmitter (8 MHz) when **CAS set on transmitter to Rel 16**. The modem  (1.2.0) gets synced, shows correct information about PDSCH channel but no information about MCH (PMTCH) and no stream on the output.  On TU Braunschweig / R&S receiver signal  is decoded and multicast stream is on the output.

We also tried Sample Stream from:

https://github.com/5G-MAG/Documentation-and-Architecture/wiki/Sample-Files

for Rel 16

https://obeca-testdaten.s3.eu-central-1.amazonaws.com/8MHz_MCS16_1kHz25_Rel16.raw

and saw the same results. Please see the attached files @dsilhavy @kuehnhammer  

We might have a wrong settings somewhere but when Rel 14 set on Tx then it works.

Thank you.
Michal

![Rel_16_Screenshot from 2022-03-16 14-23-42](https://user-images.githubusercontent.com/95072705/158607680-955d3186-7313-4116-9f18-01fb3826827d.png)
![Rel_16_Screenshot from 2022-03-16 14-24-14](https://user-images.githubusercontent.com/95072705/158607705-bf96a5c2-95f9-4149-9bd1-d6a73a35c706.png)

**Comment by m-bures** [comment] 2022-03-18 13:24
One thing that I omitted and didn’t specify. 

I was referring to Rel-16 implementation in terms of Rel-16 CAS but using numerologies of Rel 14 i.e. 1,25 kHz and 7,5 kHz (not 370 Hz or 2,5 kHz).

We tried with 1,25 kHz SC, the recording in Sample Files is with 7,5 kHz.

I don't know whether it makes any difference @kuehnhammer

**Comment by dsilhavy** [comment] 2022-03-18 13:47
As discussed in the developers call: Rel-16 CAS is currently not supported in the rt-mbms-modem.

**Comment by kuehnhammer** [comment] 2023-10-05 10:49
Duplicate of #9, #10, #11

**Comment by dsilhavy** [comment] 2023-11-17 10:12
Closing as covered in #9 #10 and #11. We keep progress in the dedicated issues

**Closed by dsilhavy** 2023-11-17 10:12 UTC
Labels: duplicate
