### ISSUE TITLE
Cyclic prefix duration 300 microseconds

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-mbms-modem#13] opened 2021-11-01 08:46 UTC
### Description
Cyclic Prefix duration 300 microseconds and a symbol duration of 3ms

### Background & Important terms
tbd

### Implementation steps & recommendations
tbd

### Related specifications
* ETSI TS 103 720

**Comment by kuehnhammer** [comment] 2023-10-05 10:48
Duplicate of #6

**Closed** 2023-11-17 09:48 UTC
Labels: duplicate, enhancement
