### ISSUE TITLE
Cyclic Prefix duration 200 microseconds

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-mbms-modem#12] opened 2021-11-01 08:45 UTC
### Description
Cyclic Prefix duration 200 microseconds and symbol duration of 1ms

### Background & Important terms
tbd

### Implementation steps & recommendations
tbd

### Related specifications
* ETSI TS 103 720

**Comment by kuehnhammer** [comment] 2023-10-05 10:47
Duplicate of #6

**Closed** 2023-11-17 09:48 UTC
Labels: duplicate, enhancement
